global:
  scrape_interval:     10s
  evaluation_interval: 10s

# initial
# scrape_configs:
#  - job_name: 'prometheus'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:9090']


scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['java:8080']
